name: store_jacoco_site
inputs:
  module:
    required: false
runs:
  using: composite
  steps:
  - uses: actions/upload-artifact@v4.1.0
    with:
      path: "${{ inputs.module }}/target/site/jacoco/index.html"
  - uses: actions/upload-artifact@v4.1.0
    with:
      path: "${{ inputs.module }}/target/site/jacoco/jacoco-resources"