name: mvn_jar_deploy
runs:
  using: composite
  steps:
  - uses: actions/checkout@v4.1.0
  - name: Adjust pom version
    run: ".circleci/adjust-pom-version.sh"
    shell: bash
  - name: restore_cache
    uses: actions/cache@v3.3.2
    with:
      key: v1-dependencies-{{ checksum "pom.xml" }}
      path: UPDATE_ME
      restore-keys: v1-dependencies-{{ checksum "pom.xml" }}
  - name: Run Maven Jar Deploy
    run: mvn -s .circleci/mvn-settings.xml -T4 flatten:flatten jar:jar deploy:deploy
    shell: bash
  - name: save_cache
    uses: actions/cache@v3.3.2
    with:
      path: "~/.m2"
      key: v1-dependencies-{{ checksum "pom.xml" }}