name: mvn_jar_deploy
runs:
  using: composite
  steps:
  - uses: actions/checkout@v4.1.0
  - name: Adjust pom version
    run: ".circleci/adjust-pom-version.sh"
    shell: bash
  - name: restore_cache
    uses: actions/cache@v3.3.2
    with:
      key: v1-dependencies-{{ checksum "pom.xml" }}
      path: UPDATE_ME
      restore-keys: v1-dependencies-{{ checksum "pom.xml" }}
  - name: Setup GPG for signing
    env:
      GPG_PRIVATE_KEY: ${{ env.GPG_PRIVATE_KEY }}
    shell: bash
    run: |
      mkdir -p ~/.gnupg
      echo 'pinentry-mode loopback' > ~/.gnupg/gpg.conf
      chmod 600 ~/.gnupg/gpg.conf
      echo "$GPG_PRIVATE_KEY" | gpg --batch --import
  - name: Run Maven Central Deploy
    env:
      CENTRAL_USERNAME: ${{ env.CENTRAL_USERNAME }}
      CENTRAL_PASSWORD: ${{ env.CENTRAL_PASSWORD }}
      GPG_PASSPHRASE: ${{ env.GPG_PASSPHRASE }}
      GPG_KEYNAME: ${{ env.GPG_KEYNAME }}
    run: mvn -s .github/mvn-settings-central.xml -P release -B -T4 -DskipTests -Dgpg.keyname="$GPG_KEYNAME" -Dgpg.passphrase="$GPG_PASSPHRASE" deploy
    shell: bash
  - name: save_cache
    uses: actions/cache@v3.3.2
    with:
      path: "~/.m2"
      key: v1-dependencies-{{ checksum "pom.xml" }}