version: 2.1

executors:
  java17:
    docker:
      - image: 'cimg/openjdk:17.0'

orbs:
  maven: circleci/maven@1.3.0

jobs:
  maven_package: ## delete this if maven/test works
    executor: java17
    steps:
      # todo - ssh keys?
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Build with tests
          command: |
            mvn clean package
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
  github_release:
    executor: java17
    steps:
      - maven/test:
          executor: java17

workflows:
  main:
    jobs:
      - maven/test:
          name: run_tests
          executor: java17
      - maven/test:
          name: deploy_to_github
          executor: java17
          command: 'deploy -DskipTests'
          settings_file: .circleci/mvn-settings.xml
          context:
            - Production
          requires:
            - run_tests
          filters:
            branches:
              only: circleci-project-setup ## todo - change to main
