name: mvn_verify
runs:
  using: composite
  steps:
  - uses: actions/checkout@v4.1.0
  - name: restore_cache
    uses: actions/cache@v3.3.2
    with:
      key: v1-dependencies-{{ checksum "pom.xml" }}
      path: UPDATE_ME
      restore-keys: v1-dependencies-{{ checksum "pom.xml" }}
  - name: Run Maven Verify (no sample)
    run: mvn -s .circleci/mvn-settings.xml -T4 verify
    shell: bash
  - uses: "./.github/actions/store_jacoco_site"
    with:
      module: qqq-backend-core
  - uses: "./.github/actions/store_jacoco_site"
    with:
      module: qqq-backend-module-filesystem
  - uses: "./.github/actions/store_jacoco_site"
    with:
      module: qqq-backend-module-rdbms
  - uses: "./.github/actions/store_jacoco_site"
    with:
      module: qqq-backend-module-api
  - uses: "./.github/actions/store_jacoco_site"
    with:
      module: qqq-middleware-api
  - uses: "./.github/actions/store_jacoco_site"
    with:
      module: qqq-middleware-javalin
  - uses: "./.github/actions/store_jacoco_site"
    with:
      module: qqq-middleware-picocli
  - uses: "./.github/actions/store_jacoco_site"
    with:
      module: qqq-middleware-slack
  - uses: "./.github/actions/store_jacoco_site"
    with:
      module: qqq-language-support-javascript
  # Sample project coverage is only available when built with -P withSample
  - name: Save test results
    run: |-
      mkdir -p ~/test-results/junit/
      find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
    if: always()
    shell: bash
  - uses: actions/upload-artifact@v4.1.0
    with:
      path: "~/test-results"
  - name: save_cache
    uses: actions/cache@v3.3.2
    with:
      path: "~/.m2"
      key: v1-dependencies-{{ checksum "pom.xml" }}