name: Kingsrook/qqq/deploy
on:
  push:
    branches:
    - release
jobs:
  mvn_deploy:
    runs-on: ubuntu-latest
    env:
      CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
      CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: "./.github/actions/install_java17"
    - uses: "./.github/actions/mvn_verify"
    - uses: "./.github/actions/mvn_jar_deploy"
  publish_asciidoc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: "./.github/actions/install_asciidoctor"
    - uses: "./.github/actions/run_asciidoctor"
    - uses: "./.github/actions/upload_docs_site"
