name: Kingsrook/qqq/test_only
on:
  push:
    branches:
    - release
jobs:
  mvn_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: "./.github/actions/install_java17"
    - uses: "./.github/actions/mvn_verify"
